[project]
name = "aws-s3-rds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.39.4",
    "streamlit>=1.46.1",
]
